language: python
sudo: required
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'create database nonogram;'
services:
  - mysql
script:
  - export SQLALCHEMY_DATABASE_URI=mysql://root:@localhost/nonogram
  - coverage run --source . -m pytest -v && coverage report
after_success:
  coveralls
notifications:
  email: false
